/**
 * Video CMS Types
 */

export interface Video {
    id: string;
    title: string;
    description: string;
    category: VideoCategory;
    tags: string[];

    // File info
    fileName: string;
    fileSize: number; // bytes
    duration: number; // seconds
    thumbnail: string;
    videoUrl: string;

    // Status
    status: VideoStatus;
    uploadProgress?: number;
    transcodingProgress?: number;

    // Metadata
    uploadedBy: string;
    uploadedAt: string;
    publishedAt?: string;

    // Analytics
    views: number;
    totalWatchTime: number; // seconds
    averageWatchPercentage: number; // 0-100

    // AI features
    transcript?: string;
    autoGeneratedCaption?: boolean;
    keyMoments?: VideoMoment[];

    // Related content
    errorCodeIds?: string[]; // Linked error codes
    relatedVideos?: string[]; // Video IDs

    createdAt: string;
    updatedAt: string;
}

export type VideoStatus =
    | 'uploading'
    | 'processing'
    | 'transcoding'
    | 'ready'
    | 'failed'
    | 'archived';

export type VideoCategory =
    | 'tutorial'
    | 'troubleshooting'
    | 'maintenance'
    | 'installation'
    | 'training'
    | 'product_demo';

export interface VideoMoment {
    timestamp: number; // seconds
    title: string;
    description: string;
    thumbnail?: string;
}

export interface VideoStats {
    totalVideos: number;
    totalDuration: number; // seconds
    totalViews: number;
    totalWatchTime: number; // seconds
    averageEngagement: number; // percentage
    videosByCategory: Record<VideoCategory, number>;
    videosByStatus: Record<VideoStatus, number>;
    topVideos: VideoPerformance[];
}

export interface VideoPerformance {
    id: string;
    title: string;
    views: number;
    watchTime: number;
    engagement: number;
}

export interface WatchSession {
    id: string;
    videoId: string;
    userId: string;
    startedAt: string;
    endedAt?: string;
    watchedDuration: number; // seconds
    completionPercentage: number; // 0-100
    lastPosition: number; // seconds
}

export interface VideoSearchResult {
    videoId: string;
    title: string;
    matchType: 'title' | 'description' | 'transcript' | 'tags';
    snippet: string;
    relevanceScore: number;
    timestamp?: number; // For transcript matches
}
